server:
  port: 10010

spring:
  application:
    name: spring-ai-alibaba-moonshot-chat-model-example

  ai:
    moonshot:
      base-url: "https://api.moonshot.cn"
      api-key: ${MOONSHOT_API_KEY}
