server:
  port: 10002

spring:
  application:
    name: spring-ai-alibaba-qwq-chat-client-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

      chat:
        options:
          model: qwq-plus
