spring:
  ai:
    alibaba:
      toolcalling:
        baidutranslate:
          enabled: true
          app;-id: ${BAIDU_TRANSLATE_APP_ID}
          secret-key: ${BAIDU_TRANSLATE_SECRET_KEY}

    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
