services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: spring-ai-alibaba-redis
    volumes:
      # - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis-stand.conf
    command: redis-server /etc/redis/redis-stand.conf
